// <auto-generated />
using ArbitrageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArbitrageApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250407190740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArbitrageApp.Models.ArbitrageOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BinancePrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoinbasePrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CryptoComPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KrakenPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PercentDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("ArbitrageOpportunities");
                });
#pragma warning restore 612, 618
        }
    }
}
